### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by ehtashamGH** [ringlesoft/laravel-process-approval#11]
Facing this error continuously.
Experimenting on laravel version 10.

![image](https://github.com/ringlesoft/laravel-process-approval/assets/50701518/47f19b81-d831-43a3-a727-6e0c865554be)

**Comment by ringunger** [comment]
Hello @ehtashamGH, What version of the package are yo using?
Can you try to upgrade to the latest version?

**Comment by ehtashamGH** [comment]
> Hello @ehtashamGH, What version of the package are yo using?
> Can you try to upgrade to the latest version?

Latest one I guess via composer command. I think it fetches latest version of the package?
But the error was genuine inside laravel version 10. I manually give int vals to test the package.
Like the error was add step function expecting model and role id integers.
But the code was throwing model name and role name strings.

**Comment by ringunger** [comment]
The latest version uses Laravel Prompt.  But the screenshot you shared doesn't seem to be using laravel prompts.

Here is a screenshot

<img width="637" alt="image" src="https://github.com/ringlesoft/laravel-process-approval/assets/6137527/fbf2e215-4cb9-4057-b844-47bf68e59484">
