### ISSUE TITLE
Also not working upon composer require package in laravel 9

### ISSUE THREAD

**Issue by ehtashamGH** [ringlesoft/laravel-process-approval#12]
The Package is not working with older versions of laravel. My is laravel 9.
Can you help?

**Comment by ringunger** [comment]
This package only supports Laravel 10.0 or later. I will include this in the README file.
Thanks

**Comment by ehtashamGH** [comment]
> This package only supports Laravel 10.0 or later. I will include this in the README file.
> Thanks

Hm. Any possibilities to work inside laravel 9?
