### ISSUE TITLE
approvalsPaused

### ISSUE THREAD

**Issue by Omkartomar93** [ringlesoft/laravel-process-approval#14]
i am facing issue when i debug $model->approvalsPaused 
then i got false 

<img width="641" alt="image" src="https://github.com/ringlesoft/laravel-process-approval/assets/114276193/d891a386-4184-4bfb-afe1-04d9908d15ac">
![image](https://github.com/ringlesoft/laravel-process-approval/assets/114276193/42a506cf-c53a-468d-9dd6-353510a6f7a6)

**Comment by ringunger** [comment]
if you want to pause approvals for a particular model, define a method ```pauseApprovals()``` and return true. By default this is ```false```. <br>
Example:
```php
public function pauseApprovals: bool 
{
// TODO write a logic to decide whether to pause approvals
return true;
}
```

**Comment by ehtashamGH** [comment]
@ringunger and what about this method in Approvable Trait.

```
    /**
     * Enables pausing the approval process for intermediate actions
     * @return mixed
     */
    public function getApprovalsPausedAttribute(): mixed
    {
        if (method_exists($this, 'pauseApprovals')) {
            return $this->pauseApprovals();
        }
        return false;
    }
```
    
I do not see the `approvalsPaused ` column/attribute being set up anywhere in the package files. Where exactly to set this attribute?

**Comment by ringunger** [comment]
You should define a method ```pauseApprovals()``` in your model that
returns true if approvals are paused.
it is not an actual model attribute.
