### ISSUE TITLE
About Approval Data

### ISSUE THREAD

**Issue by Parvez8700** [ringlesoft/laravel-process-approval#17]
Dear Team,

I hope this message finds you well. I am currently working on implementing the Laravel Process Approval package in my application. I have successfully created process_approval_flows and process_approval_flow_steps, and I have added the required traits to my model.

However, I am facing an issue with the frontend not displaying any data. However process_approval_statuses table is containg the data created by model. But, I am unable to view any data on the frontend.

Here are some key details about my implementation:

Database Tables:

process_approvals
process_approval_flows
process_approval_flow_steps
process_approval_statuses
Implemented Traits:

I have added the necessary traits to my model.
Issue:

The frontend is not displaying any data, and the process_approval_statuses table contains data.
I have checked the roles i am logged in with the correct role but not data reflecting.
I have reviewed the documentation and checked my code, but I am unable to identify the source of the problem. I would appreciate your guidance and assistance in resolving this issue.

If possible, could you provide insights into how the process_approval table is expected to be populated, and any steps or considerations I might be missing in the implementation?

Thank you for your time and assistance. I look forward to hearing from you soon.

Best regards,

Parvez Alam
Software Engineer

**Comment by ringunger** [comment]
Hello @Parvez8700 
Thanks for reaching out.

Firstly, I would like to know how you have implemented the code at the front-end (blade). This will give me a clearer picture of what issues you are facing.

The expected implementation is by adding the following to the detailed view (show) of your model.
```
<x-ringlesoft-approval-actions :model="$modelInstance" />
```

**Comment by Parvez8700** [comment]
Dear David,

I appreciate your consideration. I've successfully resolved the issue, and this package has proven to be fantastic. It has saved me a significant amount of time. Thank you very much.

Regards,
Parvez Alam

**Comment by ringunger** [comment]
Thanks
