### ISSUE TITLE
[Question] Add a "Return to previous approver" step in the approval process

### ISSUE THREAD

**Issue by PrasadChinwal** [ringlesoft/laravel-process-approval#18]
I want to check if its possible to add a "Return to previous approver" step using this package?

My workflow:
- Approval has 3 steps. 
- `employee -> manager -> cio`
- I want the `manager` to be able to return the form to `employee` for corrections. So can CIO return it to the manager.

Is this possible?

**Comment by ehtashamGH** [comment]
@ringunger can you please respond on this?

**Comment by ringunger** [comment]
Hello @ehtashamGH this is not directly possible for now. 
I'm working on it and will probably be available in the next version.

**Comment by ringunger** [comment]
I have implemented this in v1.0.8.
If you find any issues please report.

**Comment by PrasadChinwal** [comment]
Thanks @ringunger 😊 Will test this out soon.
