### ISSUE TITLE
Permissions option over Role?

### ISSUE THREAD

**Issue by tonypartridge** [ringlesoft/laravel-process-approval#21]
I see here you have the role_id which works well. But also you have a permissions column, is there any reason why the permissions column which is a json store. Is there functionality to use permissions over roles? We use teams you see, and using roles means we need a global role. Opposed to just using existing roles, so a permission would be better. i.e. for us to check this user has permission to approval the model for X permission.

@ringunger ?

**Comment by ringunger** [comment]
Hello @tonypartridge I'm working on this feature and will be available in the coming versions. The column is there but not usable yet.

**Comment by tonypartridge** [comment]
> Hello @tonypartridge I'm working on this feature and will be available in the coming versions. The column is there but not usable yet.

Great to hear, let me know if you need help. I have helped Eightynite on his package into filament for you package see:
https://filamentphp.com/plugins/eightynine-approvals

I was also wondering about extending your package, to allow skipping to steps based on models fillable values.

i.e. is step = 2, model type value changes to 3 go to step 1 and so on.

**Comment by ehtashamGH** [comment]
@ringunger @tonypartridge 
Guys how to achieve this using this package:

Can we revert the flow back to the initiate step for any changes and then back to the approver who asked for changes?
