### ISSUE TITLE
ProcessApprovedListener Notifications

### ISSUE THREAD

**Issue by Mohammed-800** [ringlesoft/laravel-process-approval#39]
If you have an approval process that requires more than one person to approve in a particular sequence, and you want to send notifications to everyone in the sequence when the previous step is approved, how can you implement this?

**Comment by ringunger** [comment]
Have you checked the [documentation](https://github.com/ringlesoft/laravel-process-approval?tab=readme-ov-file#notifying-approvers) ?

**Comment by ringunger** [comment]
By default, the package enables you to notify the immediate (next) approvers. The rest of the approvers will be notified when  the process is waiting for their actions.

Here, 'Next approvers' means at a particular step, multiple people could have the same authority to approve the resource. Any of them can approve it.

**Comment by Mohammed-800** [comment]
@ringunger 
ok ,also How to add more ApprovalTypeEnum?

**Comment by ringunger** [comment]
You can't for now. Unless you modify the code
