### ISSUE TITLE
submit controller has user table hard coded for validation

### ISSUE THREAD

**Issue by UsaidMuhammad** [ringlesoft/laravel-process-approval#41]
![image](https://github.com/user-attachments/assets/14a1bb38-3c68-4cf2-95d0-f4bf433da589)

As you can see above users table is hard coded for validation, there is an option to provide us custom model to act as a user table but we need this validation to be dynamic as well since our project's users table has a different name.

**Comment by ringunger** [comment]
Thanks @UsaidMuhammad
I'll fix this.

**Comment by ringunger** [comment]
Resolved In v1.0.9
