### ISSUE TITLE
Best Practice for Implementing Silence-as-Consent in Approval Processes

### ISSUE THREAD

**Issue by digitall-it** [ringlesoft/laravel-process-approval#43]
I am currently exploring the best way to implement a "**silence-as-consent**" approach using this package. Specifically, I would like to create an approval process where _if an agent does not respond within a specified time frame, the request is automatically approved (or rejected)_.

Could you please advise on the **suggested best practice** for achieving this using your package? Any **insights** or **examples** would be greatly appreciated.

Thank you for your time and support!

**Comment by ringunger** [comment]
You can programmatically approve a model by calling the `$model->approve($comment, $user)` method.
Use a cron job that checks if the model has been approved by the particular step or not. There are multiple methods you can use, one of them is `$model->nextApprovalStep`. Also you can use the `$model->lastApproval()` method to get the time at which the last approval was done.

**Comment by ringunger** [comment]
By the way, In the next version I'll consider implementing a simple way of getting the time a model has been waiting for approval.
