### ISSUE TITLE
How to check if the model needs approval or not? 

### ISSUE THREAD

**Issue by ehtashamGH** [ringlesoft/laravel-process-approval#44]
How to check if any model upon submission needs approval or not?
@ringunger

**Comment by ehtashamGH** [comment]
@ringunger

**Comment by ringunger** [comment]
if the value returned by `$model->nextApprovalStep()` is NOT `null`.

To do it statically, check if `Model::approvalFlow()` returns a `ProcessApprovalFlow` model and it has one or more `ProcessApprovalFlowStep` steps (relation).

I'll consider simplifying this in the next versions
